### ISSUE TITLE
Adding to Arduino Library Manager

### ISSUE THREAD

**Issue by hoilett** [frejanordsiek/arduino_library_AD56X4#1]
Have you thought about adding this to the Arduino library manager?

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by frejanordsiek** [comment]
The last time I worked with this library was before the library manager existed. I don't have the hardware anymore to test it, so it would be hard to know if it works reliably anymore (Issue #2  seems to suggest it has a bug).
