### ISSUE TITLE
word errors

### ISSUE THREAD

**Issue by andrewkhardy** [frejanordsiek/arduino_library_AD56X4#2]
I'm getting errors both in the example and in the driver everytime it casts to word. 

The errors read
 undefined reference to `makeWord(unsigned short)'
collect2: error: ld returned 255 exit status

**Comment by frejanordsiek** [comment]
It seems the issue is how I was using the function ```word()``` to cast to ```word``` rather than standard casts. Evidently what worked back in 2013 no longer does.

I've fixed the casts in commits 5c8e596 and 9e60ecd.

Can you check if that fixes the issue for you? I no longer have the hardware with which to test it.
